build: Added legacy_hw_disk_encryption
*This commit fixed:
error: vendor/qcom/opensource/cryptfs_hw/Android.bp:14:1:
"libcryptfs_hw" depends on undefined module
"legacy_hw_disk_encryption_defaults"